version: "3.4"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: prepared
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db
  iamp:
    image: iamp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      DB_HOST: 127.0.0.1
      DB_PORT: 3307
    ports:
      - 80:8080
    depends_on:
      - db
